### PR TITLE
Misc improvements

### LINKED ISSUE #4819: 115/阿里云跨网盘秒传
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

请问是否可以实现阿里云和115之间的跨网盘妙传。目前两个网盘的秒传思路好像是一样的。CD2就支持这个功能。

### Suggested solution / 实现思路

_No response_

### Additional context / 附件

_No response_

### LINKED ISSUE #4934: 中国移动云盘无法在线播放，但是能下载
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as `Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.24.0

### Driver used / 使用的存储驱动

中国移动云盘

### Describe the bug / 问题描述

添加中国移动云盘之后无法网页播放，但是能下载，webdav也可以播放、下载

### Reproduction / 复现链接

链接：https://caiyun.139.com/m/i?135CmW2qwc9GE
提取码：emuP 
复制本段信息，打开最新版「中国移动云盘APP」即可获取，超大空间随心存，移动用户免流量。

### Config / 配置

302定向到云盘

### Logs / 日志

_No response_

### LINKED ISSUE #4938: Modified date is changed when file is uploaded to AList
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as `Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.24.0

### Driver used / 使用的存储驱动

Local

### Describe the bug / 问题描述

Every file that I upload to AList, gets a new `Modified` timestamp. It doesn't matter if I'm uploading via web interface or WebDav client, the timestamp is changed.

image

Original file:
image

It's important for me to preserve the original date 🙏 

### Reproduction / 复现链接

?

### Config / 配置

TrueNAS Chart

### Logs / 日志

_No response_

### PR DESCRIPTION
**Pull request by SeanHeuc**
general: add createTime/updateTime support in webdav and some drivers
general: add hash support in some drivers
general: cross-storage rapid-upload support
general: enhance upload to avoid local temp file if possible
general: replace readseekcloser with File interface to speed up stream operations
feat(aliyun_open): same as above
feat(crypt): add hack for 139cloud

Close #4934 
Close #4938 
Close #4819 

baidu_netdisk  need to improve upload code to support rapid-upload

### CODE REVIEW

**Comment by SeanHeuc** [comment]
upload and related stream process is complicated, it's hard to come up with a good-for-all solution. most drivers need to be updated to support rapid-upload (if they support it). pls help review, help refactor, or bring up better ideas and i will implement it.

**Comment by SeanHeuc** [comment]
i guess i have to fix the 115 driver myself for now, i'll have to copy many function from author's repo to our code base, hope this won't violate any license

**Comment by xhofe** [comment]
> i guess i have to fix the 115 driver myself for now, i'll have to copy many function from author's repo to our code base, hope this won't violate any license

It's the MIT license and shouldn't be violated

**Comment by SeanHeuc** [comment]
115 driver has been upgraded to adapt the latest code.

**Review by xhofe — APPROVED** [review]

**Pull request merged**
