### PR TITLE
feat: build index & search with bleve (#1740)

### PR DESCRIPTION
**Pull request by BoYanZh**
Indexing is very slow, most time is spent on network requests. Tested on <https://alist.52qy.repl.co/>, it took 9 hours to index 614416 files.

Searching is very fast, only took <50ms to list 100 results.

### CODE REVIEW

**Comment by BoYanZh** [comment]
@Xhofe I need some hints on how to pass the CodeFactor check. I just copy lines from https://github.com/alist-org/alist/blob/b51e66454368b4543ae18d00a60c062e6fb95ebc/server/webdav/file.go#L90 and https://github.com/alist-org/alist/blob/a24dfddc2aa3499148f0840afd92f8b20905a59b/server/webdav.go#L43 .

**Comment by Xhofe** [comment]
> @Xhofe I need some hints on how to pass the CodeFactor check. I just copy lines from
> 
> https://github.com/alist-org/alist/blob/b51e66454368b4543ae18d00a60c062e6fb95ebc/server/webdav/file.go#L90
> 
> and
> https://github.com/alist-org/alist/blob/a24dfddc2aa3499148f0840afd92f8b20905a59b/server/webdav.go#L43
> 
> .

You can leave it out for now and fix it all together later.

**Comment by Xhofe** [comment]
Only storing file names in data seems to have no way to do search in a specified directory? Or is there something I haven't noticed?
To do that, we need to store the filename and parent dir of the file in data, and the id needn't to care about so that maybe a uuid is just ok.

Another thing to think about is how to incrementally update the index

one more thing, why set the filename field to `parent`?

**Comment by BoYanZh** [comment]
> Only storing filename in data seems to have no way to do search in a specified directory? Or is there something I haven't noticed? To do that, we need to store the filename and parent dir of the file in data, and the id needn't to care about so that maybe a uuid is just ok.

According to https://blevesearch.com/docs/Query/ , I have tried Prefix search and Conjunction search, which does not perform well. The search results rely heavily on the tokenizer.

> Another thing to think about is how to incrementally update the index

It seems hard to do it with bleve only.

> one more thing, why set the filename field to `parent`?

Fixed.

**Comment by Xhofe** [comment]
it's probably not as convenient as relational databases yet if that's the case?

**Comment by BoYanZh** [comment]
For now, in my prespective there is no need to consider any other demands except for searching. Following the worse is better philosophy, further functionality can be added later.
File searching tools like Everything do not have an option to rebuild the index either partly. Maybe there is no hurry to implement that, just warn the user that build the index might be very time-consuming is enough.

**Comment by BoYanZh** [comment]
Since bleve used kv database to store the documents, partial update can be done with manually traverse through it.

**Comment by Xhofe** [comment]
What do you mean by "Prefix search and Conjunction search don't perform well". Is there something wrong with them?

**Comment by BoYanZh** [comment]
It can not return all the results with a certain prefix. Only when the prefix is very short, it will work. When the prefix grows bigger, nothing will return.

**Comment by BoYanZh** [comment]
> What do you mean by "Prefix search and Conjunction search don't perform well". Is there something wrong with them?

More specifically, it turns out that the prefix query in bleve will match the documents in which the query string eqauls to content of the first token (though a document may have multiple first tokens as it can be tokenized in different ways). So if the prefix is longer than one token, then it will never be matched by any of the documents.

**Pull request merged**
