### PR TITLE
fix: fix cannot connect to Casdoor SSO bug

### PR DESCRIPTION
**Pull request by hsluoyz**
Fix: https://github.com/alist-org/alist/issues/4266

https://user-images.githubusercontent.com/3787410/235297865-5b77094f-23ad-4b5f-bce3-5f2249ced716.mp4

### CODE REVIEW

**Comment by hsluoyz** [comment]
@anwen-anyi hi, can you test if the three problems mentioned in your issue are fixed in this PR?

**Comment by anwen-anyi** [comment]
> @anwen-anyi hi, can you test if the three problems mentioned in your issue are fixed in this PR?

Okay, I'm going to test it now. Does this solve any of the three problems I raised or all of them?
But the second one may be caused by my own problem, you can ignore it first, sorry for misleading you

**Comment by anwen-anyi** [comment]
ok, perfect fix  :kissing_heart: :kissing_heart:  :ok_hand:

**Comment by hsluoyz** [comment]
@anwen-anyi I cannot reproduce the 3rd problem as your video after this fix. Did you see it happen again with this fix?

**Comment by anwen-anyi** [comment]
Sorry, I saw the video you posted at the beginning and thought it was only the second one. I tested it just now and it turned out that the third one was also fixed. :kissing_heart: :kissing_heart: :kissing_heart: :kissing_heart: :kissing_heart:

**Pull request merged**
