### PR TITLE
fix(drivers/iLanZou): resolve resource access issue on iLanZou drive

### LINKED ISSUE #6271: 蓝奏云优享版的bug
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.33.0

### Driver used / 使用的存储驱动

蓝奏云优享版

### Describe the bug / 问题描述

添加蓝奏云优享版之后
挂在的根目录为/蓝奏云
然后在里面创建新的文件夹
在alist里面新创建的文件夹路径上会自动嵌套一个同名文件夹。而这个同名文件夹其实映射的是根目录挂载的。
比如，我在/蓝奏云优享 这个根目录里新创建了一个测试文件夹
出现的 /蓝奏云优享/测试 其实跟/蓝奏云 是一样的
/蓝奏云/测试/测试 这个才是新创建的文件夹。
image

而蓝奏云优享版那边其实只在根目录下有一个测试 文件夹。并没有实质上生成嵌套的两个文件夹
image

### Reproduction / 复现链接

……

### Config / 配置

……

### Logs / 日志

_No response_

### LINKED ISSUE #6415: 蓝奏云优享版failed link: failed get link: redirect failed, status: 200
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

编译最新开发版32

### Driver used / 使用的存储驱动

蓝奏云优享版

### Describe the bug / 问题描述

提示失败链接：失败 获取链接：重定向失败，状态：200

### Reproduction / 复现链接

image

### Config / 配置

无

### Logs / 日志

image

### PR DESCRIPTION
**Pull request by lanytcc**
The driver failed to mount due to incorrect URL parameter ordering which the backend did not accept

This commit reorders the parameters to meet the backend's expectations

and ensures successful mounting of the iLanZou driver.

Closes #6271, Closes #6415

### CODE REVIEW

**Comment by huolanyun** [comment]
顺便把小飞机也修复一下

**Comment by lanytcc** [comment]
> 顺便把小飞机也修复一下

修了, 他俩一块的, 合了就能用了

**Review by xhofe — APPROVED** [review]

**Comment by huolanyun** [comment]
> > 顺便把小飞机也修复一下
> 
> 修了, 他俩一块的, 合了就能用了
小飞机又挂了

**Comment by lanytcc** [comment]
@huolanyun 我回头抽空看一眼，你先提issue

**Pull request merged**
