### PR TITLE
Improve: make docker release 10 times faster

### PR DESCRIPTION
**Pull request by Mmx233**
Compiling Golang in QEMU is not very efficient, and parallel compilation can lead to insufficient memory, resulting in extensive use of swap. Using Golang's cross-compilation to directly compile binaries for various architectures not only avoids the aforementioned issues but also eliminates the need for multiple downloads of dependencies.

This is a test of the action's execution status. In this CI run, in addition to the content of the current pull request, ffmpeg was also installed, resulting in a total duration of 7 minutes and 4 seconds: https://github.com/Mmx233/alist/actions/runs/7396976799/job/20123220627

### CODE REVIEW

**Comment by xhofe** [comment]
This doesn't seem to have cgo enabled?

**Comment by Mmx233** [comment]
> This doesn't seem to have cgo enabled?

CGO not support cross-compilation in default. If there is no function require CGO enabled, then keep it disabled is better. I have tested the image in linux/amd64 environment, it's running normally. And I simultaneously built Docker images for both the original configuration and the new configuration, with the new image being slightly smaller than the previous one.

**Comment by xhofe** [comment]
But CGO is required for sqlite3

**Comment by Mmx233** [comment]
Cross-compilation has been switched to use musl gcc in cgo.

**Comment by Mmx233** [comment]
The new build method for releasing Docker takes approximately 12 minutes.
https://github.com/Mmx233/alist/actions/runs/7410639734

**Review by xhofe — APPROVED** [review]

**Pull request merged**
