### PR TITLE
feat: add `febbox` driver

### PR DESCRIPTION
**Pull request by Three-taile-dragon**
### 添加 `FebBox` 网盘驱动

#7293

官方网站：`https://www.febbox.com`

官方开放平台：`https://www.febbox.com/open`

---

### 配置项说明
- `Root folder id`：根目录ID，默认为 `0`，可从官方Web端的地址栏中获取
  - image
  - 如图中的 `目录ID` 为：`13168737`
- `Client id`：客户端ID，从 官方网站中生成：`https://www.febbox.com/open/clients`
- `Client secret`：客户端密钥，从 官方网站中生成：`https://www.febbox.com/open/clients`
  - image
  - **注意看清楚`client_id`和`client_secret` ，不要填反了**
- `Sort rule`：排序规则
- `Page size`：单次请求的文件列表大小，默认 `100`
- `User ip`：**可选** ，用户下载时的IP，引用官方说明
  - `IP address, Optional parameter. Supports IPv6 format.After filling in, the best download server suitable for the IP location will be selected. If not filled in, the requested IP will be used.`
  - `IP地址，可选参数。支持 IPv6 格式。填写后，将选择适合 IP 位置的最佳下载服务器。如果未填写，将使用请求的 IP。`

---

### 注意事项
- 目前上传功能不可用：https://github.com/alist-org/alist/issues/7293#issuecomment-2395776474

### CODE REVIEW

**Comment by outsider1997** [comment]
你好，下载的时候报错

2024/11/04 14:23:24 [Recovery] 2024/11/04 - 14:23:24 panic recovered:
runtime error: index out of range [0] with length 0

runtime/debug.Stack()
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/runtime/debug/stack.go:24 +0x5e
github.com/alist-org/alist/v3/pkg/singleflight.newPanicError({0x2400a20, 0xc000bc8960})
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:35 +0x25
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2.1()
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:188 +0x34
panic({0x2400a20?, 0xc000bc8960?})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/runtime/panic.go:770 +0x132
github.com/alist-org/alist/v3/drivers/febbox.(*FebBox).getDownloadLink(0xc000002c00, {0xc0012284c8, 0x8}, {0xc001228530, 0xd})
	/home/runner/work/alist/alist/drivers/febbox/util.go:139 +0x285
github.com/alist-org/alist/v3/drivers/febbox.(*FebBox).Link(0xc000002c00, {0xc00004f0e8?, 0x41acf8?}, {0x3cf4a08?, 0xc000baf200?}, {{0xc001228600, 0xd}, 0xc000d5dce0, {0x0, 0x0}, ...})
	/home/runner/work/alist/alist/drivers/febbox/driver.go:74 +0x79
github.com/alist-org/alist/v3/internal/op.Link.func1()
	/home/runner/work/alist/alist/internal/op/fs.go:258 +0x5e
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2(0xc000bced20, 0x7f806f477108, 0x50?)
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:193 +0x66
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall(0xc000ab6f60?, 0xc001306720?, {0xc001306720?, 0xc000745d40?}, 0x3d163a0?)
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:195 +0xa5
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do(0x3d0fe20, {0xc001306720, 0x2f}, 0xc00004f290)
	/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:108 +0x16f
github.com/alist-org/alist/v3/internal/op.Link({0x3cea4b0, 0xc000a28800}, {0x3cf57e0, 0xc000002c00}, {0xc000c0a4c9, 0x28}, {{0xc001228600, 0xd}, 0xc000d5dce0, {0x0, ...}, ...})
	/home/runner/work/alist/alist/internal/op/fs.go:276 +0x419
github.com/alist-org/alist/v3/internal/fs.link({0x3cea4b0, 0xc000a28800}, {0xc000c0a4c2?, 0x25b2ba0?}, {{0xc001228600, 0xd}, 0xc000d5dce0, {0x0, 0x0}, 0xc0008f1320})
	/home/runner/work/alist/alist/internal/fs/link.go:19 +0x105
github.com/alist-org/alist/v3/internal/fs.Link({0x3cea4b0?, 0xc000a28800?}, {0xc000c0a4c2, 0x2f}, {{0xc001228600, 0xd}, 0xc000d5dce0, {0x0, 0x0}, 0xc0008f1320})
	/home/runner/work/alist/alist/internal/fs/fs.go:48 +0x65
github.com/alist-org/alist/v3/server/handles.Down(0xc000a28800)
	/home/runner/work/alist/alist/server/handles/down.go:33 +0x1a6
github.com/gin-gonic/gin.(*Context).Next(...)
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server/middlewares.Down(0xc000a28800)
	/home/runner/work/alist/alist/server/middlewares/down.go:40 +0x2bb
github.com/gin-gonic/gin.(*Context).Next(...)
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded(0xc000a28800)
	/home/runner/work/alist/alist/server/middlewares/check.go:14 +0xbb
github.com/gin-gonic/gin.(*Context).Next(...)
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1(0xc000a28800)
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/recovery.go:102 +0x7a
github.com/gin-gonic/gin.(*Context).Next(...)
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc000a28800)
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/logger.go:249 +0xe5
github.com/gin-gonic/gin.(*Context).Next(...)
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000b596c0, 0xc000a28800)
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633 +0x892
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000b596c0, {0x3ce3f90, 0xc000dae620}, 0xc0008f1320)
	/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589 +0x1b2
net/http.serverHandler.ServeHTTP({0xc000d5c570?}, {0x3ce3f90?, 0xc000dae620?}, 0x6?)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc000bae3f0, {0x3cea050, 0xc000bfe300})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 102
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/net/http/server.go:3285 +0x4b4

/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:165 (0x95a552)
/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:200 (0x965c01)
/home/runner/work/alist/alist/pkg/singleflight/singleflight.go:108 (0x96614e)
/home/runner/work/alist/alist/internal/op/fs.go:276 (0x94f7f8)
/home/runner/work/alist/alist/internal/fs/link.go:19 (0xdfa024)
/home/runner/work/alist/alist/internal/fs/fs.go:48 (0xdf9004)
/home/runner/work/alist/alist/server/handles/down.go:33 (0x1c670a5)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x1c346ba)
/home/runner/work/alist/alist/server/middlewares/down.go:40 (0x1c34623)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x1c3417a)
/home/runner/work/alist/alist/server/middlewares/check.go:14 (0x1c34168)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0xde6d99)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/recovery.go:102 (0xde6d87)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0xde5ec4)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/logger.go:249 (0xde5eab)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 (0xde52b1)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633 (0xde4d20)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589 (0xde4851)
/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/net/http/server.go:3137 (0x7672ed)
/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/net/http/server.go:2039 (0x7625c7)
/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/runtime/asm_amd64.s:1695 (0x479f60)

**Comment by Three-taile-dragon** [comment]
> 你好，下载的时候报错
> 
> 2024/11/04 14:23:24 [Recovery] 2024/11/04 - 14:23:24 panic recovered: runtime error: index out of range [0] with length 0
> 
> runtime/debug.Stack() /home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/runtime/debug/stack.go:24 +0x5e github.com/alist-org/alist/v3/pkg/singleflight.newPanicError({0x2400a20, 0xc000bc8960}) /home/runner/work/alist/alist/pkg/singleflight/singleflight.go:35 +0x25 github.com/alist-

咋弄出来的，我这边测试，下载正常啊

**Comment by outsider1997** [comment]
新建文件夹、删除、移动都没问题，下载就报错 Request failed with status code 500，后端报错是我上面发那个..

**Comment by gui1gui** [comment]
> 新建文件夹、删除、移动都没问题，下载就报错 Request failed with status code 500，后端报错是我上面发那个..

大佬，我也这样，请问大佬你解决了吗？

**Pull request merged**
